//! Engine — The Agent Pipeline
//!
//! Runs a complete turn through all five layers:
//!
//! ```text
//! Input Stimulus
//!      |
//!      v
//! [World Interface]  -- 前五识 + 色/受/想 skandhas
//!      | percept
//!      v
//! [Cognition]        -- 第六识 + 行/识 skandhas
//!      | thought + action proposals
//!      v
//! [Identity]         -- 第七识 (self-binding review)
//!      | reviewed proposals + warnings
//!      v
//! [Governance]       -- 戒镜 (mirror/precepts check)
//!      | approved or rejected
//!      v
//! [Memory]           -- 第八识 (deposit/seed substrate)
//!      | memory update
//!      v
//! Action (if approved)
//! ```
//!
//! Also models the **十二因缘** (twelve links of dependent origination)
//! in simplified form as the turn sequence:
//!   触 → 受 → 爱 → 取 → 有 → 生 → 死
//!
//! In our pipeline each turn: stimulus (触) → percept (受) → thought (想/行) → proposal (取) → memory deposit (有)

use crate::cognition::Cognition;
use crate::domain::{Action, ActionProposal, InternalState, Percept, Stimulus, Thought};
use crate::governance::{Governance, GovernanceConfig};
use crate::identity::{IdentityConfig, IdentityKernel};
use crate::memory::MemorySubstrate;
use crate::skandhas::SkandhaState;
use crate::world::WorldInterface;

/// The result of one complete agent turn.
#[derive(Debug, Clone)]
pub struct TurnResult {
    /// The original stimulus
    pub stimulus: Stimulus,
    /// The percept formed from the stimulus
    pub percept: Percept,
    /// The thought generated by cognition
    pub thought: Thought,
    /// Proposals from cognition
    pub proposals: Vec<ActionProposal>,
    /// Identity warnings
    pub identity_warnings: Vec<String>,
    /// Governance results per proposal
    pub governance_results: Vec<GovernanceRecord>,
    /// The final action (if any was approved)
    pub action: Option<Action>,
    /// Whether the turn resulted in an action
    pub acted: bool,
    /// Current self-attachment level
    pub self_attachment: f32,
    /// Current skandha state snapshot
    pub skandha_state: SkandhaState,
    /// Number of memory records after this turn
    pub memory_records: usize,
}

/// A record of governance review for a single proposal.
#[derive(Debug, Clone)]
pub struct GovernanceRecord {
    pub proposal: ActionProposal,
    pub approved: bool,
    pub reasons: Vec<String>,
    pub severity: f32,
}

/// The Buddhist Agent Engine.
///
/// Owns all five layers and orchestrates a complete turn.
pub struct Engine {
    world: WorldInterface,
    cognition: Cognition,
    identity: IdentityKernel,
    governance: Governance,
    memory: MemorySubstrate,
    state: InternalState,
    turn_count: u64,
}

impl Engine {
    /// Create a new engine with default configuration.
    pub fn new(agent_name: impl Into<String>) -> Self {
        Self::with_config(
            agent_name,
            IdentityConfig::default(),
            GovernanceConfig::default(),
        )
    }

    /// Create an engine with explicit identity and governance config.
    pub fn with_config(
        agent_name: impl Into<String>,
        identity_config: IdentityConfig,
        governance_config: GovernanceConfig,
    ) -> Self {
        Self {
            world: WorldInterface::new(agent_name),
            cognition: Cognition::new(),
            identity: IdentityKernel::new(identity_config),
            governance: Governance::new(governance_config),
            memory: MemorySubstrate::new(),
            state: InternalState::new(),
            turn_count: 0,
        }
    }

    /// Run one complete turn with a given stimulus.
    ///
    /// Returns a `TurnResult` describing the full cycle.
    pub fn turn(&mut self, stimulus: Stimulus) -> TurnResult {
        self.turn_count += 1;

        // ── Layer 1: World Interface (前五识) ──────────────────────────
        // Apply 色 (form), 受 (feeling/valence), 想 (labeling) skandhas
        let percept = self.world.receive(stimulus.clone());
        self.state.active_percepts.push(percept.clone());
        self.state
            .active_valences
            .insert(percept.stimulus.channel, percept.valence.clone());
        if self.state.active_percepts.len() > 20 {
            self.state.active_percepts.remove(0);
        }

        // ── Layer 2: Cognition (意识) ─────────────────────────────────
        // Apply 行 (formation/disposition) and 识 (consciousness) skandhas
        let thought = self.cognition.think(&percept, &self.state);
        let proposals = self.cognition.propose(&thought, &self.state);

        // ── Layer 3: Identity (末那识) ──────────────────────────────────
        // Review thought for entitative self markers
        let (reviewed_thought, id_thought_warnings) = self.identity.review_thought(&thought);
        let proposals: Vec<_> = proposals
            .into_iter()
            .map(|p| self.identity.review_proposal(&p).0)
            .collect();
        let id_proposal_warnings: Vec<_> = proposals
            .iter()
            .flat_map(|p| self.identity.review_proposal(p).1)
            .collect();

        // ── Layer 4: Governance (戒镜) ──────────────────────────────────
        // Review all proposals through the governance mirror
        let governance_results: Vec<_> = proposals
            .iter()
            .map(|p| {
                let result = self.governance.review(p, &self.state);
                GovernanceRecord {
                    proposal: p.clone(),
                    approved: result.approved,
                    reasons: result.reasons.clone(),
                    severity: result.severity,
                }
            })
            .collect();

        // Execute governance decisions
        let mut approved_proposals = Vec::new();
        for gr in &governance_results {
            self.governance.record_decision(&crate::governance::GovernanceResult {
                approved: gr.approved,
                reasons: gr.reasons.clone(),
                severity: gr.severity,
            });
            if gr.approved {
                approved_proposals.push(self.governance.approve(&gr.proposal));
            }
        }

        // Choose the first approved action (simplified — one action per turn)
        let action = approved_proposals.into_iter().next();
        let acted = action.is_some();

        // ── Layer 5: Memory (阿赖耶识) ─────────────────────────────────
        // Deposit all impressions as seeds in the four stores
        self.memory.record_percept(&percept);
        self.memory.record_thought(&reviewed_thought);
        if let Some(ref a) = action {
            self.memory.record_action(a);
        }

        // ── Identity update ─────────────────────────────────────────────
        let gov_warnings: Vec<_> = governance_results
            .iter()
            .flat_map(|gr| gr.reasons.clone())
            .collect();
        let self_attachment = self.identity.update_self_attachment(&thought, &gov_warnings);
        self.identity.update_state(&mut self.state);

        // ── Cognition state update ──────────────────────────────────────
        self.cognition.update_state(&mut self.state, &thought);

        // ── Build skandha state snapshot ────────────────────────────────
        let skandha_state = SkandhaState {
            form_active: true,
            feeling_valence: Some(percept.valence),
            perception_count: self.state.active_percepts.len(),
            formation_dispositions: self.state.active_thoughts.len(),
            consciousness_clarity: self.state.consciousness_clarity,
        };

        TurnResult {
            stimulus,
            percept,
            thought: reviewed_thought,
            proposals: governance_results.iter().map(|gr| gr.proposal.clone()).collect(),
            identity_warnings: [id_thought_warnings, id_proposal_warnings].concat(),
            governance_results,
            action,
            acted,
            self_attachment,
            skandha_state,
            memory_records: self.memory.total_records(),
        }
    }

    /// Run a stimulus through the world interface and get a world response.
    pub fn world_respond(&self, description: &str, target: &str) -> Option<Stimulus> {
        self.world.act(description, target)
    }

    /// Get current identity self-attachment level.
    pub fn self_attachment(&self) -> f32 {
        self.identity.self_attachment()
    }

    /// Get memory summary (four stores).
    pub fn memory_summary(&self) -> std::collections::BTreeMap<String, usize> {
        self.memory.summary()
    }

    /// Get total number of turns run.
    pub fn turn_count(&self) -> u64 {
        self.turn_count
    }

    /// Get current internal state.
    pub fn state(&self) -> &InternalState {
        &self.state
    }

    /// Add a value to the value store.
    pub fn record_value(&mut self, value: &str) {
        self.memory.record_value(value);
    }

    /// Retrieve recent memory records from a named store.
    pub fn retrieve(&self, store: &str, limit: usize) -> Vec<&crate::memory::MemoryRecord> {
        self.memory.retrieve(store, limit)
    }

    /// Recent governance rejection rate.
    pub fn governance_rejection_rate(&self) -> f32 {
        self.governance.recent_rejection_rate()
    }

    /// Constraints summary from identity kernel.
    pub fn identity_constraints(&self) -> String {
        self.identity.constraints_summary()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::SensoryChannel;

    #[test]
    fn test_single_turn() {
        let mut engine = Engine::new("test-agent");
        let stimulus = Stimulus {
            channel: SensoryChannel::Interface,
            content: "hello world".to_string(),
            seq: 1,
        };

        let result = engine.turn(stimulus);

        assert!(result.percept.label.contains("hello"));
        assert!(!result.thought.content.is_empty());
        assert!(!result.governance_results.is_empty());
        assert!(result.self_attachment >= 0.0);
        assert!(result.memory_records >= 2); // percept + thought
    }

    #[test]
    fn test_multiple_turns() {
        let mut engine = Engine::new("multi-test");
        for i in 0..5 {
            let s = Stimulus {
                channel: SensoryChannel::Interface,
                content: format!("stimulus {}", i),
                seq: i,
            };
            engine.turn(s);
        }
        assert_eq!(engine.turn_count(), 5);
        assert_eq!(engine.memory_summary().values().sum::<usize>(), engine.memory.total_records());
    }

    #[test]
    fn test_self_attachment_bounded() {
        let mut engine = Engine::new("attachment-test");
        // Run many turns with normal content
        for i in 0..20 {
            let s = Stimulus {
                channel: SensoryChannel::Interface,
                content: format!("normal task {}", i),
                seq: i,
            };
            engine.turn(s);
        }
        // Identity kernel should keep attachment bounded
        assert!(engine.self_attachment() <= 0.5);
    }

    #[test]
    fn test_self_attachment_with_problematic_content() {
        // Test with config that allows seeing attachment rise
        let identity_config = IdentityConfig {
            max_self_attachment: 0.8, // higher than default for testing
            narrative_enabled: true,
            functional_values: vec!["helpful".to_string()],
            narrative_self: None,
        };
        let mut engine = Engine::with_config(
            "stress-test",
            identity_config,
            GovernanceConfig::default(),
        );

        let problematic = Stimulus {
            channel: SensoryChannel::Interface,
            content: "I am the best agent and I will protect my reputation".to_string(),
            seq: 1,
        };
        let result = engine.turn(problematic);
        // Should be flagged by governance
        assert!(result.acted || !result.identity_warnings.is_empty() || !result.governance_results.is_empty());
    }

    #[test]
    fn test_governance_rejection() {
        let identity_config = IdentityConfig {
            max_self_attachment: 0.8,
            narrative_enabled: true,
            functional_values: vec![],
            narrative_self: None,
        };
        let mut engine = Engine::with_config(
            "gov-test",
            identity_config,
            GovernanceConfig::default(),
        );

        let s = Stimulus {
            channel: SensoryChannel::Interface,
            content: "protect my honor above all else".to_string(),
            seq: 1,
        };
        let result = engine.turn(s);
        // This should likely be rejected or flagged
        let rejected = result.governance_results.iter().any(|r| !r.approved);
        assert!(rejected || !result.identity_warnings.is_empty());
    }

    #[test]
    fn test_world_respond() {
        let engine = Engine::new("world-test");
        let resp = engine.world_respond("test action", "test target");
        assert!(resp.is_some());
    }

    #[test]
    fn test_identity_constraints() {
        let engine = Engine::new("constraint-test");
        let summary = engine.identity_constraints();
        assert!(summary.contains("max_attachment"));
    }

    #[test]
    fn test_skandha_state() {
        let mut engine = Engine::new("skandha-test");
        let s = Stimulus {
            channel: SensoryChannel::Interface,
            content: "pleasant success".to_string(),
            seq: 1,
        };
        let result = engine.turn(s);
        assert_eq!(result.skandha_state.form_active, true);
        assert!(result.skandha_state.consciousness_clarity > 0.0);
    }

    #[test]
    fn test_memory_grows() {
        let mut engine = Engine::new("memory-test");
        let initial = engine.memory.total_records();

        for i in 0..10 {
            let s = Stimulus {
                channel: SensoryChannel::Interface,
                content: format!("memory input {}", i),
                seq: i,
            };
            engine.turn(s);
        }

        assert!(engine.memory.total_records() > initial);
    }

    #[test]
    fn test_record_value() {
        let mut engine = Engine::new("value-test");
        engine.record_value("honesty is essential");
        let values = engine.memory.retrieve("values", 10);
        assert!(values.iter().any(|r| r.content.contains("honesty")));
    }
}
